# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170531_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b'documents/%Y/%m/%d'),
        ),
    ]
