# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170531_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b'logo'),
        ),
    ]
